domain_root = "foo.net"
subdomain_to_update = "home"
# to update the root A record
#update_domain_root = "true"
update_interval = "30mins"
digital_ocean_token = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz"
dry_run = "false"
