# Build
[tasks.default]
depends = ["build:backend"]
description = "Build the binary"

[tasks."build:backend_minimal"]
description = "Build the minimal binary"
run = "cargo build "

[tasks."build:backend"]
description = "Build the web-enabled binary"
run = "cargo build --features web"
wait_for = ["build:web"]

[tasks."build:web"]
description = "Build the web frontend"
run = "npm run build"
dir = "{{config_root}}/webclients/svelte"

[tasks."build:all"]
description = "Build the binary and web frontend"
depends = ["build:backend", "build:web"]


# Gen
[tasks."gen:openapi"]
description = "Generate the open api schema"
run = "npm run apigen"
dir = "{{config_root}}/webclients/svelte"

[tasks."gen:changelog"]
description = "Update changelog using git cliff"
run = 'git cliff -o CHANGELOG.md'


# Release
[tasks."release"]
description = "Create new git tag based on version returned by git cliff"
run = 'git tag $(git cliff --bumped-version)'


# Run
[tasks."run:backend_minimal"]
description = "Run the binary"
run = "cargo run"

[tasks."run:backend"]
description = "Run the binary"
run = "cargo run --features web"


# Test
[tasks."test:backend"]
description = "Test the binary"
run = "cargo test --features web"


# Lint
[tasks."lint:backend"]
description = "Lint the backend code"
run = "cargo clippy --features web"

[tasks."lint:web"]
description = "Lint the web frontend code"
run = "npm run lint && npm run check"
dir = "{{config_root}}/webclients/svelte"

[tasks."lint:all"]
description = "Lint the backend and web frontend code"
depends = ["lint:backend", "lint:web"]

[tasks."format:backend"]
description = "Format the backend"
run = "cargo fmt"

[tasks."format:backend:check"]
description = "Check that the backend is formatted"
run = "cargo fmt --check"

[tasks."check:all"]
description = "Build the backend, run tests, and lint the code"
run = [
    { task = "build:backend" },
    { task = "test:backend" },
    { task = "format:backend:check" },
    { task = "lint:backend" },
    { task = "build:web" },
    { task = "lint:web" },
]

# Update deps
[tasks."bump:backend:semver"]
description = "Update backend dependencies according to semver compatibility"
run = "cargo upgrade"

[tasks."bump:backend:breaking"]
description = "Update backend dependencies according to latest versions, ignoring semver"
run = "cargo upgrade --incompatible"

[tasks."bump:backend:lockfile"]
description = "Update backend lockfile"
run = "cargo update"

[tasks."bump:web:semver"]
description = "Update web dependencies according to semver compatibility"
run = 'npm-check-updates --target semver --upgrade && npm install'
dir = "{{config_root}}/webclients/svelte"

[tasks."bump:web:breaking"]
description = "Update web dependencies according to latest versions, ignoring semver"
run = 'npm-check-updates --upgrade && npm install'
dir = "{{config_root}}/webclients/svelte"
