name: 'Create archive'
description: 'Create staging archive'
inputs:
  rust_target_arch:
    description: 'Rust target arch'
    required: true
  archive_suffix:
    description: 'Suffix to add to archive name'
    default: ''
outputs:
  archive_name:
    description: "Staging archive name"
    value: ${{ steps.build_staging_archive.outputs.asset }}
runs:
  using: "composite"
  steps:
    - name: Build staging archive
      id: build_staging_archive
      shell: bash
      run: |
        ARTIFACT_NAME=do_ddns
        echo "ARTIFACT_NAME is: ${ARTIFACT_NAME}"
        echo "ARTIFACT_NAME=${ARTIFACT_NAME}" >> $GITHUB_ENV

        ARTIFACT_PATH=$(cargo metadata --format-version 1 | jq -r '.target_directory')/${{ inputs.rust_target_arch }}/release/${ARTIFACT_NAME}
        echo "ARTIFACT_PATH is: ${ARTIFACT_PATH}"
        echo "ARTIFACT_PATH=${ARTIFACT_PATH}" >> $GITHUB_ENV

        RELEASE_VERSION=$(awk -F ' = ' '$1 ~ /version/ { gsub(/[\"]/, "", $2); printf("%s",$2) }' Cargo.toml)
        echo "RELEASE_VERSION is: ${RELEASE_VERSION}"
        echo "RELEASE_VERSION=${RELEASE_VERSION}" >> $GITHUB_ENV

        staging="${ARTIFACT_NAME}-${RELEASE_VERSION}-${{ inputs.rust_target_arch }}${{ inputs.archive_suffix }}"
        mkdir -p "$staging"
        cp {README.md,LICENSE} "$staging/"
        cp "${ARTIFACT_PATH}" "$staging/"
        tar czf "$staging.tar.gz" "$staging"
        ASSET="$staging.tar.gz"
        echo "asset=$(echo $ASSET)" >> $GITHUB_OUTPUT
